version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_user
      - MYSQL_DATABASE=chronos
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-pmysql_user']
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    depends_on:
      mysqldb:
        condition: service_healthy

    build: .
    env_file: ./.env
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - DB_HOST=mysqldb
      - DATABASE_URL=mysql://root:mysql_user@mysqldb:3306/chronos
    stdin_open: true
    tty: true

  web:
    depends_on:
      - api
    build: ../web
    ports:
      - '3000:3000'
    env_file: ../web/.env.local
    stdin_open: true
    tty: true

volumes:
  db:
